Strip out editable installs forcefully
moneymeets/python-poetry-buildpack pull request #21
Opened 2020-10-20 07:34 UTC by furious-luke

Keeping editable installs in the resultant `requirements.txt` file can
cause issues when installing from local directories. This manifests as
a missing module error for `setuptools`.

This change pipes the output of poetry export through sed to remove
any "-e " prefixes.

This isn't the exact same issue, but adds a little context: https://github.com/python-poetry/poetry/issues/897

2020-10-21 13:09 UTC, zyv requested changes
Hi @furious-luke, I'm concerned about your original pattern - this would remove `-e ` everywhere, including in the middle of the line.

I understand that `-e ` should only occur at the beginning of the lines in the context of editable dependencies. Does my pattern work for you?

I would like to avoid possible disruption for other users/cases in as much as possible...

2020-10-21 13:09 UTC, zyv commented on bin/compile
> +poetry export -f requirements.txt --without-hashes | sed 's/-e //' > requirements.txt
```suggestion
# poetry exports local dependencies as editable by default (https://github.com/python-poetry/poetry/issues/897)
poetry export -f requirements.txt --without-hashes | sed -e 's/^-e //' > requirements.txt
```

2020-10-22 12:19 UTC, stohrendorf commented on bin/compile
> +poetry export -f requirements.txt --without-hashes | sed 's/-e //' > requirements.txt
:+1:

2020-10-23 05:56 UTC, marns93 commented on bin/compile
> +poetry export -f requirements.txt --without-hashes | sed 's/-e //' > requirements.txt
+1

2020-10-25 06:16 UTC, furious-luke commented on bin/compile
> +poetry export -f requirements.txt --without-hashes | sed 's/-e //' > requirements.txt
@zyv Yep, that works for me, thanks!

2020-10-25 09:41 UTC, zyv approved these changes

2020-10-25 09:41 UTC, closed without merging

2020-10-25 09:42 UTC, zyv commented
@furious-luke thanks for your contribution!